// Shared defaults for popup.js, bridge.js and background.js
const SNCL_DEFAULTS = {
  dark: true,
  descriptionAtBottom: true,
  showEmailTab: false,
  startTab: 'work_notes',
  markCallerReplies: true,
  groupLists: true,
  enforcePrefs: true,
  enforceEnglish: true,
  paneWidth: 360,
  filterEnabled: true,
  postTypes: ['Additional comments', 'Attachments', 'Relationship changes', 'Work notes'],
};
const SNCL_POST_TYPES = [
  'Additional comments',
  'Attachments',
  'Emails - autogenerated',
  'Emails - correspondence',
  'Field changes',
  'Relationship changes',
  'Work notes',
];
